### ISSUE TITLE
Unable to bring up ONTAP 9.13

### ISSUE THREAD

**Issue by johnhenriksson** [tcler/ontap-simulator-in-kvm#1]
I'm trying to use the automation to bring up ONTAP on a CentOS 7 KVM box but it fails and I can not understand why. The CPU in the machine is Sandy Bridge so that shouldn't be a problem.

The terminal output is on this pastebin https://pastebin.com/EXi5RY2v 

Thanks for any help

**Comment by tcler** [comment]
We can not bring up ONTAP-9.9 and higher Version on RHEL-7, I guess a higher QEMU version may be needed;
see: https://github.com/tcler/kiss-vm-ns/blob/master/utils/make-ontap-simulator.sh#L27

RHEL-8 is already very stable, it is recommended to upgrade to RHEL-8.
If you dislike the hassle of registering for a Red Hat developer subscription, you can try Rocky-8;

I am using Fedora-38 Mate, also works fine : )

**Comment by johnhenriksson** [comment]
OK so if I upgrade to Rocky-8 then I should be able to deploy 9.13?

**Comment by tcler** [comment]
> OK so if I upgrade to Rocky-8 then I should be able to deploy 9.13?

9.11 is sure to be OK.  
but we haven't got 9.12, 9.13 yet, so I can only say that it's possible ; )

**Comment by tcler** [comment]
> OK so if I upgrade to Rocky-8 then I should be able to deploy 9.13?

Hi John  
I just got 9.12 and 9.13 images; the 9.12 can be able to startup on RHEL-8.8.0:  
```
fsqe-2nc1::*> set -privilege admin

fsqe-2nc1::> cifs share show -vserver vs1
Vserver        Share         Path              Properties Comment  ACL
-------------- ------------- ----------------- ---------- -------- -----------
vs1            c$            /                 oplocks    -        BUILTIN\Administrators / Full Control
                                               browsable
                                               changenotify
                                               show-previous-versions
vs1            cifs1         /cifs1            oplocks    -        Everyone / Full Control
                                               browsable
                                               changenotify
                                               show-previous-versions
vs1            cifs2         /cifs2            oplocks    -        Everyone / Full Control
                                               browsable
                                               changenotify
                                               show-previous-versions
vs1            ipc$          /                 browsable  -        -
4 entries were displayed.

fsqe-2nc1::> network interface show
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            fsqe-2nc1-01_clus1 
                         up/up    169.254.203.246/16 fsqe-2nc1-01  e0a     true
            fsqe-2nc1-01_clus2 
                         up/up    169.254.169.227/16 fsqe-2nc1-01  e0b     true
            fsqe-2nc1-02_clus1 
                         up/up    169.254.8.142/16   fsqe-2nc1-02  e0a     true
            fsqe-2nc1-02_clus2 
                         up/up    169.254.230.66/16  fsqe-2nc1-02  e0b     true
fsqe-2nc1
            cluster_mgmt up/up    192.168.20.11/24   fsqe-2nc1-01  e0d     true
            fsqe-2nc1-01_mgmt1 
                         up/up    10.73.180.184/23   fsqe-2nc1-01  e0c     true
            fsqe-2nc1-02_mgmt1 
                         up/up    10.73.180.187/23   fsqe-2nc1-02  e0c     true
vs1
            lif1.0       up/up    192.168.20.21/24   fsqe-2nc1-01  e0e     true
            lif1.1       up/up    10.73.181.117/23   fsqe-2nc1-01  e0f     true
            lif2.0       up/up    192.168.20.22/24   fsqe-2nc1-02  e0e     true
            lif2.1       up/up    10.73.180.250/23   fsqe-2nc1-02  e0f     true
11 entries were displayed.

fsqe-2nc1::> 
fsqe-2nc1::> exit
Goodbye


Connection to 192.168.20.11 closed.
NETAPP_NAS_HOSTNAME=ontap2-b407
NETAPP_NAS_IP=10.73.181.117
NETAPP_NAS_IP_LOC=192.168.20.21
NETAPP_NFS_SHARE=/share1
NETAPP_NFS_SHARE2=/share2
NETAPP_CIFS_SHARE=cifs1
NETAPP_CIFS_SHARE2=cifs2
NETAPP_CIFS_USER=root
NETAPP_CIFS_PASSWD=Sesame~0pen
NETAPP_DOMAIN_WG=
NETAPP_CIFS_WG=FSQE
[root@hp-dl388g8-18 ~]# uname -r
4.18.0-477.10.1.el8_8.x86_64
```

But 9.13 gets stuck at somewhere:  
```
Loading kernel...
Loading configured modules...

Hit [Enter] to boot immediately, or any other key for command prompt.
Booting [x86_64/freebsd/image1/kernel]...
x86_64/freebsd/image1/kernel text=0x145fe8 text=0xa70414 text=0x17b914 data=0x3cc40 data=0x4239d0+
0x59f630 syms=[0x8+0xc5988+0x8+0x979a9]
x86_64/freebsd/image1/platform.ko size 0x7080e8 at 0x1b5e000
_
```

**Comment by tcler** [comment]
see also:  
https://community.netapp.com/t5/Simulator-Discussions/Issue-with-ONTAP-Simulator-9-13-1/td-p/446223  
https://community.netapp.com/t5/Simulator-Discussions/ONTAP-Simulator-9-13-1-doesn-t-work-after-a-reboot/td-p/446348

**Comment by tcler** [comment]
Hi @johnhenriksson 
I got it. The information on the terminal stops outputting not because the system is hung, but because the information is redirected to the console. This change is actually good news; because then we can directly use expect + 'virsh console' to complete the system setup/configuration.

But I need to rewrite some code to adapt to this change. will update the comment after finish.

**Comment by tcler** [comment]
fixed: 
https://github.com/tcler/ontap-simulator-in-kvm/commit/ffd92b2fc11e338c3260373a93f8e0b87f53e38e

**Comment by tcler** [comment]
JFYI: now with the latest [kiss-vm](https://github.com/tcler/kiss-vm-ns/blob/master/kiss-vm) we can bring up ONTAP-9.13 on Fedora-3x, RHEL/RockyLinux/AlmaLinux-{8,9}, openSUSE-15.5, debian-12.5 and latest ArchLinux.
